### ISSUE TITLE
`find_python_env_var': undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jask05** [Ekultek/whitewidow#46] opened 2016-12-29 23:38 UTC
## Issue/Enhancement/Question (be specific)
Hi there,

I've installed your tool in ParrotOS and when I try to execute it i had this message:

## Exact error message/Enhancement information
```
/home/user/tools/whitewidow/lib/helpers/sqlmap_config_helper.rb:13:in `find_python_env_var': undefined method `split' for nil:NilClass (NoMethodError)
	from /home/jask/tools/whitewidow/lib/imports/constants_and_requires.rb:59:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'
```

## Steps to reproduce if applicable or steps on what should be done
cd /home/user/tools/whitewidow

## Search query if applicable (please use exact search query)
ruby whitewidow.rb -d

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
I can't get it.

## Ruby version number (run ruby --version)
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

## Labels

 - [X] Bug
 - [ ] Encoding
 - [ ] User agent
 - [ ] Enhancement
 - [ ] Question
 - [ ] Email request

Thanks a lot!

**Comment by Ekultek** [comment] 2016-12-30 00:34
Alright do this for me:

 - What is the command you where running when you received the error?
 - Did you clone whitewidow from the repo within the last few days?
 - Run `printenv` post the output
 - Run `python --version` post the output

**Comment by jask05** [comment] 2016-12-30 07:54
Of course :) 

- **What is the command you where running when you received the error?**
```
ruby whitewidow.rb -h 
ruby whitewidow.rb -d
```
- **Did you clone whitewidow from the repo within the last few days?**
Yes, I've cloned it yesterday.
```
ls -l
total 4
drwxr-xr-x 9 jask jask 4096 Dec 30 01:27 white widow
```
- **Run printenv post the output**
```
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LANG=en_US.UTF-8
GDM_LANG=en_US.utf8
DISPLAY=:0
GTK_OVERLAY_SCROLLING=0
COLORTERM=truecolor
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=2
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/jask
USER=jask
DESKTOP_SESSION=lightdm-xsession
PWD=/home/jask/tools
HOME=/home/jask
SSH_AGENT_PID=1406
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/mate:/usr/local/share/:/usr/share/
MATE_DESKTOP_SESSION_ID=this-is-deprecated
XDG_SESSION_DESKTOP=lightdm-xsession
TERM=xterm
SHELL=/bin/bash
VTE_VERSION=4601
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CURRENT_DESKTOP=MATE
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
SHLVL=1
XDG_SEAT=seat0
LANGUAGE=en_US:en
WINDOWID=46137350
GDMSESSION=lightdm-xsession
LOGNAME=jask
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/jask/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/jask/local/bin
SESSION_MANAGER=local/parrot:@/tmp/.ICE-unix/1348,unix/parrot:/tmp/.ICE-unix/1348
OLDPWD=/home/jask/tools/whitewidow
_=/usr/bin/printenv

```
- **Run python --version post the output**
Python 2.7.13

**Comment by Ekultek** [comment] 2016-12-30 11:44
Since when does Linux separate their env PATH with ":"..? The problem being, I separated the array by ";" like a normal fucking person, but apparently it doesn't work like that on parrot. I'm going to have to play around with this a little bit before I figure it out

**Comment by Ekultek** [comment] 2016-12-30 11:55
Do you have Parrot Lite, or Parrot full?

**Comment by Ekultek** [comment] 2016-12-30 12:06
I'm going to implement a temporary fix for you, see it in the next push here shortly

**Comment by Ekultek** [comment] 2016-12-30 12:06
```
  def sqlmap_config
      command_file = File.open(SQLMAP_CONFIG_PATH, "a+")
      if command_file.read == "false"
        commands = FORMAT.prompt('Enter sqlmap commands, python sqlmap.py -m SQL_VULN.LOG')  # Temp fix for issue #46, I'm working on a permanent fix https://github.com/WhitewidowScanner/whitewidow/issues/46
        # commands = FORMAT.prompt("Enter sqlmap commands, #{extract_python_env_type} sqlmap.py -m SQL_VULN.LOG")
        default = FORMAT.prompt("Make commands default [y/N]")
        if default.downcase.start_with?("y")
          command_file.truncate(0)
          command_file.puts("#{extract_python_env_type} #{SQLMAP_PATH} -m #{SQL_VULN_SITES_LOG} #{commands}")
          FORMAT.info("Commands saved, you need to rerun --sqlmap in order for the changes to take effect")
          exit(0)
        end
      else
        FORMAT.info("Running default sqlmap commands: #{File.read(SQLMAP_CONFIG_PATH)}")
      end
    end
```

**Comment by jask05** [comment] 2016-12-30 15:49
It works!! Thanks a lot =) 

PS: Mac has PATH with ":" `PATH=/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin`

**Comment by Ekultek** [comment] 2016-12-30 15:52
No problem, leave this open though because I'm still working on a permanent fix for it.

**Comment by Ekultek** [comment] 2016-12-30 20:17
So far:

```
#require_relative '../../lib/imports/constants_and_requires'

#
# sqlmap configuration, figure out if you have python installed or not
#
class SqlmapConfigHelper

  #
  # Python isn't real... It's just a conspiracy to make people believe they're hackers..
  #
  class PythonNotImplementedException < NotImplementedError
  end

  class << self

    def verify_operating_system
      data = RUBY_PLATFORM
      if data[/cygwin|mswin|mingw|bccwin|wince|emx/]
        true
      else
        false
      end
    end

    def find_python_env_var_windows
      py_path = [] # Results of the python env variables
      env_vars = ENV.to_h
      items = env_vars.to_s.split(/[^a-zA-Z0-9\/\\]/) # Split the environment variables into an array
      items.each { |var|
        if var.include?('Python')
          py_path.push(var)
        end
      }
      py_path.each { |python|
        if python.include?('2.7')
          return true
        elsif python.include?('3')
          return false
        else
          raise PythonNotImplementedException("Python must be installed before you can run sqlmap!") #Go here: #{PYTHON_DOWNLOAD_LINK}")
        end
      }
    end

    def find_python_version_linux
      version_string = system('python', '--version')
      if version_string.to_s.include?('2.7')
        return true
      elsif version_string.to_s.include?('3')
        return false
      else
        raise PythonNotImplementedException("Python must be installed before you can run sqlmap!") #Go here: #{PYTHON_DOWNLOAD_LINK}"
      end
    end

    def decisions_decisions
      if !(verify_operating_system)
        find_python_version_linux
      else
        find_python_env_var_windows
      end
    end

    def create_var_path
      if verify_operating_system
        ENV['python27'] = 'C:\\Python27'
      else
        ENV['python27'] = 'usr/local/bin'
      end
    end

  end

end

SqlmapConfigHelper.decisions_decisions
```

Just trying to figure out how to get Linux to work the way I want it to.

**Comment by Ekultek** [comment] 2016-12-31 00:30
Going to mark this as duplicate and add your issue to the sqlmap config issue

**Comment by Ekultek** [comment] 2016-12-31 00:31
Duplicate of #45

**Closed as completed by Ekultek** 2016-12-31 00:31 UTC
Labels: duplicate
