### ISSUE TITLE
Issue running the script

### ISSUE THREAD

**Issue by peterpt** [Ekultek/whitewidow#35] opened 2016-12-17 11:06 UTC
root@station1:/tools/sql/whitewidow# ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
root@station1:/tools/sql/whitewidow# ruby whitewidow.rb 
whitewidow.rb:61: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...      Hey now my friend, I know you're eager, I am also, but...
...                               ^
whitewidow.rb:62: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      either doesn't exist, or it's not in the di...
                    ^
whitewidow.rb:62: syntax error, unexpected keyword_or
      either doesn't exist, or it's not in the directory yo...
                              ^
whitewidow.rb:62: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...t in the directory you say it's in..
...                               ^
whitewidow.rb:67: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      Don't worry I'll wait!
           ^
whitewidow.rb:69: syntax error, unexpected tIDENTIFIER, expecting keyword_end
             .yellow.bold  # Error out because the file doesn't exist
                                                               ^
root@station1:/tools/sql/whitewidow# 

https://s28.postimg.org/fgyggedlp/tools_sql_whitewidow_001.png

Does the script need an higher version of ruby ?

**Comment by Ekultek** [comment] 2016-12-17 13:07
Did you even look?

https://github.com/WhitewidowScanner/whitewidow/blob/master/docs/self_help/syntax.txt

**Comment by Ekultek** [comment] 2016-12-17 13:10
Duplicate of #25, whitewidow requires at least Ruby 2.3.1 to run due to squiggly heredocs

**Closed as completed by Ekultek** 2016-12-17 13:10 UTC
Labels: duplicate, Solved

**Comment by peterpt** [comment] 2016-12-17 14:26
"Did you even look?
https://github.com/WhitewidowScanner/whitewidow/blob/master/docs/self_help/syntax.txt"

Nop , sorry , i totally missed that one , but i fixed it because i had to install new version of ruby to put the new metasploit-framework git working on my wheezy distro of kali , and then i decided to check out the whitewidow script to see if it worked with new ruby version or not , then i realized that the problem was that ruby version was not the required one and then i came here to post , and then was when i saw you message over "syntax" file .
Anyway , after installing ruby 2.3.3 problem was solved .

Sere it is the terminal screenshot 
https://s24.postimg.org/jlukj17et/whitewidow_ruby233.png

Thanks for the script and for the help .

**Comment by Ekultek** [comment] 2016-12-17 14:51
It's all good man don't worry about, I'll add rescue for that, which will specify that you need a certain ruby version, if you wouldn't mind could you make a issue with the template and say that I need a rescue for the syntax error? I would greatly appreciate it and you'd go under the contributors list. If you have a moment it'd be awesome, thanks ahead of time

**Comment by peterpt** [comment] 2016-12-17 16:38
sorry , i am not understanding the point .
Do you want me to write all the procedures i made from ruby 2.0.0 to ruby 2.3.3 that lead to a "whitewidow" script running ?

**Comment by Ekultek** [comment] 2016-12-17 16:43
Don't worry about it I'll do it thanks

**Comment by peterpt** [comment] 2016-12-17 16:50
i can do it if you want , i just did not understated the objective .

Basically the process is this 

#:curl -sSL https://get.rvm.io | bash -s stable --ruby
#:/bin/bash --login
#:rvm install 2.3.3
#:rvm use 2.3.3

then goto whitewidow directory and issue the command "bundle install"

in case of key error with curl then use this command 
gpg --keyserver hkp://keys.gnupg.net --recv-keys \ 409B6B1796C275462A1703113804BB82D39DC0E3

If i remember correctly , these were all the steps i made to make it working .

**Comment by Ekultek** [comment] 2016-12-17 23:39
You're good he objective was to make an enhancement for the rescue of the syntax error, got it covered thanks
