### ISSUE TITLE
Enhancment: Add country filter suffix

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#5] opened 2016-04-09 08:01 UTC
Lets say I want only com, co.uk, .ng, etc... it would be cool to have a parameter for that

**Comment by Ekultek** [comment] 2016-04-09 08:05
I can do that, it'll be released in the next version though.

**Comment by Ekultek** [comment] 2016-04-09 08:39
I'm going to add 20 of each that you specified for testing purposes, if you want anymore added let me know.

**Comment by Ekultek** [comment] 2016-04-09 16:57
Issue moved to here, they have been added, now I Want to keep tabs on them: https://github.com/Ekultek/whitewidow/issues/7

**Comment by Ekultek** [comment] 2016-09-09 00:07
Duplicate of #7

**Closed as completed by Ekultek** 2016-09-09 00:07 UTC
Labels: duplicate
