### ISSUE TITLE
Could not find nokogiri-1.6.8 in any of the sources

### ISSUE THREAD

**Issue by cacaocaca** [Ekultek/whitewidow#47] opened 2017-01-16 22:08 UTC
Before you create an issue please make sure that there are no issues that relate to your issue. if there is an issue that relates to one, please add a comment to that issue and describe your specific problem. If your issue has to do with any sort of installation or syntax errors, please read the self_help under the docs directory. If none of those answer your question, make an issue
--
Linux kali 4.8.0-kali1-686-pae #1 SMP Debian 4.8.5-1kali1 (2016-11-04) i686 GNU/Linux

## Exact error message/Enhancement information

ruby whitewidow.rb 
Could not find nokogiri-1.6.8 in any of the sources
Run `bundle install` to install missing gems.
root@kali:~/Scrivania/whitewidow# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed,
and installing your bundle as root will break this application for
all non-root users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Using addressable 2.4.0
Using safe_yaml 1.0.4
Using diff-lcs 1.2.5
Using unf_ext 0.0.7.2
Using hashdiff 0.3.0
Using mime-types-data 3.2016.0521
Using net-http-digest_auth 1.4
Using net-http-persistent 2.9.4
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using ntlm-http 0.1.1
Using webrobots 0.1.2
Using netrc 0.11.0
Using rspec-support 3.5.0
Using vcr 3.0.0
Using bundler 1.12.5
Using crack 0.4.3
Using unf 0.1.4
Using mime-types 3.1
Installing nokogiri 1.6.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.6.8/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20170116-4775-u30nt9.rb extconf.rb
Using pkg-config version 1.1.7
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/nokogiri-1.6.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.6.8 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/nokogiri-1.6.8/gem_make.out
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using webmock 1.24.2
Using domain_name 0.5.20160615
An error occurred while installing nokogiri (1.6.8), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before
bundling.
root@kali:~/Scrivania/whitewidow# 

## Labels

 - [ ] Bug
 - [ ] Encoding
 - [ ] User agent
 - [ ] Enhancement
 - [ ] Question
 - [ ] Email request

**Comment by Ekultek** [comment] 2017-01-16 22:24
https://github.com/WhitewidowScanner/whitewidow/blob/master/docs/self_help/bundle_issues.txt

**Comment by Ekultek** [comment] 2017-01-16 22:25
Duplicate of #29 read the self help section in the docs before making an issue please

**Closed as completed by Ekultek** 2017-01-16 22:25 UTC
Labels: duplicate, Solved, installation issues
